### ISSUE TITLE
What is the project licence?

### ISSUE THREAD

**Issue by wonea** [jakkes/Jakkes.WebSockets#1]
I'm just wondering what licence this project comes under? MIT, GPL, LGPL, Mozilla, Apache, etc?

**Comment by jakkes** [comment]
It's not under any license, use it as you wish. I havent done anything on it for a while. If miss something let me know. 
		

		Mvh
Jakob Stigenberg
	





On Wed, May 31, 2017 at 5:16 PM +0200, "Gareth" <notifications@github.com> wrote:












I'm just wondering what licence this project comes under? MIT, GPL, LGPL, Mozilla, Apache, etc?

**Comment by jakkes** [comment]
License added
